### PR TITLE
Skip processing network videos. File path can be greater than 246 chars.

### PR DESCRIPTION
**Pull request by yartat**
@UnlimitedStack

### CODE REVIEW

**Comment by UnlimitedStack** [comment]
What if a user wants to see a 3d movie from Netflix?

**Comment by yartat** [comment]
He may activate 3D format from menu on hotkey. The most of streams do not contain any patterns for successful matching 3D format. For example stereoscopic videos on Youtube [AMAZING 3D VIDEO DIGITAL - SE SALE DE LA PANTALLA - 2](https://www.youtube.com/watch?v=s-fa4j-iAPA) from 3D channel. As you see this is a HSBS. [Direct link to 1080p](https://r5---sn-3c27ln7y.googlevideo.com/videoplayback?fexp=9416126,9420452,9422596,9423662&key=yt6&mn=sn-3c27ln7y&mm=31&ms=au&mv=m&pl=22&mt=1451508714&clen=43831984&signature=4F01603301DEA93C365B482F176A114E6B125652.A7FBD25B3406B345CA1EC8B0F0DB25B9DA0F921F&keepalive=yes&ip=91.197.171.157&requiressl=yes&sparams=clen,dur,gir,id,initcwndbps,ip,ipbits,itag,keepalive,lmt,mime,mm,mn,ms,mv,pl,requiressl,source,upn,expire&itag=137&lmt=1428031817977215&id=o-AES3IkraHNbOTUHPG9IbswOiizjK1HJ4CRGOG0wy087Z&dur=187.120&source=youtube&upn=0SkfSSuZDII&mime=video/mp4&ipbits=0&initcwndbps=3293750&expire=1451530434&gir=yes&sver=3) does not contains any 3D format pattern.
Sad but true

**Comment by UnlimitedStack** [comment]
But what about video analysis? Even if the name has no "3D" in the string, the analysis could recognize that it is a 3D movie an switch to the correct 3D format? The current IsNetworkVideo() call would prevent analysis.

**Comment by yartat** [comment]
It is possible. I'll change code and push in this pull request

**Comment by UnlimitedStack** [comment]
Very good!

**Pull request merged**
